clustering:
  algorithm: hybrid
  auto_parameter_selection: true
  auto_update_memory: true
  dbscan_noise_rescue_eps_factor: 1.02
  dbscan_noise_rescue_min_samples: 2
  dbscan_noise_rescue_min_samples_factor: 0.9
  enable_graph_refinement: true
  eps: 0.31
  final_eps_factor: 1.3
  graph_k: 8
  graph_mutual_k: true
  hdbscan_alpha: 1.0
  hdbscan_cluster_selection_epsilon: 0.05
  hdbscan_min_cluster_size: 2
  hdbscan_min_samples: 2
  high_confidence_threshold: 0.88
  high_pose_threshold: 0.8
  high_quality_threshold: 0.7
  max_cache_size: 100
  merge_min_edges: 12
  merge_similarity_threshold: 0.85
  merge_tau: 0.85
  metric: cosine
  min_samples: 2
  propagation_alpha: 0.08
  propagation_iterations: 10
  quality_weighted_clustering: true
  rescue_eps_factor: 1.1
  rescue_margin: 0.03
  rescue_neighbor_agree: 7
  rescue_tau: 0.9
  similarity_threshold: 0.8
  template_quality_threshold: 0.65
  use_multipass: true
  use_scaling: false
logging:
  file_backup_count: 5
  file_enabled: true
  file_max_size: 10485760
  format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  level: INFO
processing:
  align_size: 112
  batch_size: 64
  det_size:
  - 640
  - 640
  enable_batch_processing: true
  gpu_memory_gb: 8
  max_cache_size: 2000
  max_faces_in_memory: 15000
  max_faces_per_image: 50
  max_image_size: 1280
  max_memory_mb: 6144
  max_workers: 8
  min_blur_threshold: 100.0
  model_name: buffalo_l
  use_cuda: true
  use_flip_tta: false
quality:
  blur_threshold: 40.0
  brightness_max: 230.0
  brightness_min: 25.0
  contrast_threshold: 20.0
  enable_quality_filtering: true
